### ISSUE TITLE
Regex modifier in pft-make

### ISSUE THREAD

**Issue by dacav** [dacav/App-PFT#3]
Original issue from @luckypoem:

> hello.
> 
> but i'm happy a little earlier:
> root@localhost:/usr/local/app-pft-site# pft-make
> Unknown regexp modifier "/n" at /usr/local/bin/pft-make line 203, at end of line
> Execution of /usr/local/bin/pft-make aborted due to compilation errors.
> root@localhost:/usr/local/app-pft-site# pft make
> Unknown regexp modifier "/n" at /usr/local/bin/pft line 170, at end of line
> Unknown regexp modifier "/n" at /usr/local/bin/pft line 173, at end of line
> Execution of /usr/local/bin/pft aborted due to compilation errors.
> root@localhost:/usr/local/app-pft-site#
> 
> how to fix it?
> tks very much

**Comment by dacav** [comment]
This is an actual problem of the pft-make script. The `/n` modifier is available only in later versions of perl, but the good news is it can be replaced with a `(?:` regex modifier. Removing the `n` will also do fine.

This will require me a patch, actually, but you can survive it by simply removing the `n` modifier from all the reported regexes. I'll post here and close the issue as soon as I'll have time to fix it.

**Comment by dacav** [comment]
@luckypoem

The patch for App-PFT (version 1.2.1) is done. In a matter of hours you should be able to install via cpan the new version with a pair of fixes, including the one for this Issue.

**Comment by dacav** [comment]
Also the patch is https://github.com/dacav/App-PFT/commit/5686e1b3591fba29b4e2aa4c56cf76b404835c38

**Comment by luckypoem** [comment]
actually ,b4 u release the patach/update to version 1.2.1, i upgrade the perl in my vps to v5.22.1, then the issue is no more:
wget http://www.cpan.org/src/perl-5.22.1.tar.gz
tar zxvf perl-5.22.1.tar.gz
cd perl-5.22.1
./Configure -des -Dprefix=/usr
make
make install
perl -v

it shows:
This is perl 5, version 22, subversion 1 (v5.22.1)

then:
cpan App::PFT

then no more errors.

**Comment by dacav** [comment]
On Fri, Jun 16, 2017 at 12:52:13AM -0700, luckypoem wrote:
> then no more errors.

Well, of course if you upgrade your perl installation it's going to go away.
However pft is supposed to run on perl from 5.16 up. If you are updating
perl just for sake of running pft, I would suggest to use your distro's perl
and get App::PFT 1.2.1 instead.

You just need to run `cpan App::PFT` again, since 1.2.1 is now in the cpan
repositories.

If you decide to follow my advice, could you report me back if the fix
worked for you?

-- 
010 Giovanni [dacav] Simoni
001 <dacav@openmailbox.org>
111
    OpenPGP key: 93FC 2A6A 43A4 AAC2 0D8E 5411 2F99 ABB6 BA14 DF9E

**Comment by luckypoem** [comment]
yes, i tested in my third vps.it works:
root@ary:/usr/local/app-pft-site# pft-make
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "zh_CN.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
root@ary:/usr/local/app-pft-site# ls
build  content	inject	pft.yaml  templates
root@ary:/usr/local/app-pft-site#

by the way,how to fix the locale issue?

**Comment by dacav** [comment]
Did it work by using the Perl version provided by the operating system? If so, we can close this issue.

For the locale problem, I'll open another issue, since it's a different situation, hold on :)
(also, whenever you feel like it's a different problem, feel free to open a different issue, so any problem has its solution).

**Comment by dacav** [comment]
@luckypoem : https://github.com/dacav/App-PFT/issues/4

**Comment by luckypoem** [comment]
yes,it works by using the Perl version provided by the operating system
